name: Auto Deploy to DigitalOcean Development
run-name: ${{ github.actor }} is deploying to DigitalOcean Development
on:
  push:
    branches:
      - development
jobs:
  auto-deploy-digitalocean:
    runs-on: ubuntu-latest
    steps:
      - uses: digitalocean/app_action@v1.1.5
        with:
          app_name: j-and-j-web-development
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
