name: Auto Deploy to DigitalOcean Production
run-name: ${{ github.actor }} is deploying to DigitalOcean production
on:
  push:
    branches:
      - production
jobs:
  auto-deploy-digitalocean:
    runs-on: ubuntu-latest
    steps:
      - uses: digitalocean/app_action@v1.1.5
        with:
          app_name: j-and-j-web-production
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
